version: "3"

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: "mysql://r2dsmm:r2dsmm@db:3306/r2dsmm"
      SESSION_SECRET: "changeme"
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: r2dsmm
      MYSQL_USER: r2dsmm
      MYSQL_PASSWORD: r2dsmm
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
